MNIST_IMAGE_SIZE: int = 20
MNIST_IMAGE_BORDER_SIZE: int = 4
MNIST_IMAGE_BACKGROUND_VALUE: int = 255
MNIST_IMAGE_WITH_BORDER_SIZE: int = MNIST_IMAGE_SIZE + 2*MNIST_IMAGE_BORDER_SIZE
MNIST_IMAGE_WITH_BORDER_AREA: int = (MNIST_IMAGE_WITH_BORDER_SIZE
                                     * MNIST_IMAGE_WITH_BORDER_SIZE)
