name: Backend Workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'

  # Enable running workflow manually from Actions tab
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  backend-test:
    name: Backend Test
    uses: hfiggs/hunterfiggs.com/.github/workflows/backend-test.yml@main

  backend-deploy:
    name: Backend Deploy
    needs: backend-test
    uses: hfiggs/hunterfiggs.com/.github/workflows/backend-deploy.yml@main
    secrets: inherit
